version: "3.9"

services:
  backend:
    image: phyvathanak/nestjs-backend:latest
    container_name: domrov_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

  code_eval:
    image: phyvathanak/code_eval:latest
    container_name: domrov_code_eval
    restart: always
    env_file:
      - .env

networks:
  default:
    name: domrov_network